name: Build Python EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build main.exe
        run: pyinstaller -F --windowed main.py

      - name: Build rainbow.exe
        run: pyinstaller -F --windowed rainbow.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-exes
          path: |
            dist/main.exe
            dist/rainbow.exe
